spring:
  application:
    name: register-server-2010

server:
  port: 2010

#eureka server settings
eureka:
  instance:
    hostname: peer1
  server:
    enable-replicated-request-compression: false
    wait-time-in-ms-when-sync-empty: 0
  client:
    registry-fetch-interval-seconds: 10
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:2011/eureka,http://peer1:2010/eureka

#logging settings
#logging:
 # config: classpath:logbak-spring.xml
#logback:
#  logdir: /opt/club/apps/log/
#  appname: register-server
